export enum NotificationType {
  NEW_APPOINTMENT = 'NEW_APPOINTMENT',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  NEW_SALE = 'NEW_SALE',
  SYSTEM = 'SYSTEM'
} 